### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Dertosh**

### CODE REVIEW

**Comment by slytomcat** [comment]
Only b51fd7d looks reasonable.
980a19a - wrong (see my comments)
f74b2a4 - rather meaningless
Sorry, but i can't accept this PR.

**Comment by Dertosh** [comment]
980a19a - It's very strange, reboot after updating with the oldest version of the kernel. Or make option for sorting.
f74b2a4 - Make code more readable.

**Comment by slytomcat** [comment]
Actually using --long_option_name instead of -o[ption] increases not only readability but also length of the command.
In some cases (as in 980a19a) it may make sense, but applying it to in options of efibootmgr makes it such huge command that it becomes almost unreadable.

Mixing long and short options names - is also not a good style from my point of view. 
So, in common, I prefer short options names because even long names usually requires go look in to man-pages to be sure that you really understand what they mean.

As for kernels sorting - I know only one behavior of efibootmgr -c command: it adds newly created boot option in to beginning of BootOrder (i.e. on the 1-st position). It is described in the man (in examples section). And forward sorting works as expected on several computers where I've implemented UEFI-Boot solution.

**Comment by Dertosh** [comment]
I test this script and in my computer, and efibootmgr add boot record under first not occupied number. For example:

```
Boot0000* LinuxMint ... 4.8.XX
Boot0001* LinuxMint ... 4.4.XX
Boot0002* Windows Boot Manager
```

After using ` efibootmgr -Bb$OPT`

`Boot0002* Windows Boot Manager`

After using update code without `-r
`
```
Boot0000* LinuxMint ... 4.4.XX
Boot0001* LinuxMint ... 4.8.XX
Boot0002* Windows Boot Manager
```

After using update code with `-r
`
```
Boot0000* LinuxMint ... 4.8.XX
Boot0001* LinuxMint ... 4.4.XX
Boot0002* Windows Boot Manager
```

**Comment by slytomcat** [comment]
Very strange:
efibootmgr man tells:

> An  OS installer would call efibootmgr -c.  This assumes that /boot/efi
       is your EFI System Partition, and is mounted at /dev/sda1.   This  cre‐
       ates  a  new boot option, called "Linux", and puts it at the top of the
       boot order list.

**Comment by Dertosh** [comment]
Yes. efibootmgr puts it at the top of the boot order list. But put it in under first not occupied number, because the first number is occupied. You can test it.

**Comment by slytomcat** [comment]
Check BootOrder value. Actual sequence of boot priority is defined by BootOrder

**Comment by Dertosh** [comment]
I check  you're right. I am sorry.

**Comment by Dertosh** [comment]
I check, you're right. I am sorry.

**Pull request closed without merging**
