### PR TITLE
Fix bug with efi volume, add distributive label

### PR DESCRIPTION
**Pull request by Dertosh**
1) If efi partition isn't the first, the boot path isn't correct. I get first vfat volume and parsing for disk and part . Disk and part adding in efibootmgr parameters.

2)I add  commands for insert distributive name in parameter label. 

I hope it will be useful.

### CODE REVIEW

**Comment by slytomcat** [comment]
Thanks for your ideas.
Only one concern. If all labels are maid as --label "$DUSTRIB" then there is no way to distinguish different kernels for one distribution (all labels for all kernels will be the same).

**Comment by bam80** [comment]
@slytomcat, this is a serious consern - I always have several kernel installed at once. Maybe add kernel version to the label?

**Comment by slytomcat** [comment]
@bam80, I've already fixed this consern. See last commits in the master brunch.

**Comment by bam80** [comment]
@slytomcat, thanks. Glad you keep working on the project

**Pull request merged**
